<div class="blocks-promo">
  <a class="block-promo home-main" href="http://localhost.com/collections/yoga-new.html">
    <img src="<?php echo $this->getViewFileUrl('Magento_Cms::images/b1.png'); ?>" alt="" width="1260" height="381">
    <span class="action more button">SHOP NOW</span>
  </a>
  <div class="block-promo-wrapper block-promo-hp">
    <a class="block-promo home-pants" href="{{store url=""}}promotions/pants-all.html">
      <img src="<?php echo $this->getViewFileUrl('Magento_Cms::images/b2.png'); ?>" alt="">
      <span class="action more button">SHOP NOW</span>
    </a>
    <a class="block-promo home-t-shirts" href="{{store url=""}}promotions/tees-all.html">
      <img src="<?php echo $this->getViewFileUrl('Magento_Cms::images/b3.png'); ?>" alt=""></span>
    </a>
    <a class="block-promo home-erin" href="{{store url=""}}collections/erin-recommends.html">
       <img src="<?php echo $this->getViewFileUrl('Magento_Cms::images/b4.png'); ?>" alt="">
    </a>
    <a class="block-promo home-performance" href="{{store url=""}}collections/performance-fabrics.html">
      <img src="<?php echo $this->getViewFileUrl('Magento_Cms::images/b5.png'); ?>" alt="">
    </a>
  </div>
</div>

<div class="content-heading">
  <h2 class="title">Hot Sellers</h2>
  <p class="info">Here is what`s trending on Luma right now</p>
</div>
